"""可信度指标计算、融合和局部观测更新。"""

from .metrics import (
    ConfidenceComponent,
    ConfidenceUpdateReport,
    ConfidenceWeights,
    ObservationModelResult,
    compute_consistency_confidence,
    compute_observation_confidence,
    compute_observation_model,
    compute_recency_confidence,
    compute_resolution_confidence,
    fuse_confidence,
    update_confidence_from_observation,
)
from .config import default_confidence_config_path, load_confidence_weights
from .bayesian import (
    BayesianStateLayer,
    CategoricalBayesianStateLayer,
    TerrainLikelihoodRules,
    compute_terrain_category_likelihood,
    default_terrain_likelihood_config_path,
    derive_confidence_from_categorical_posterior,
    derive_confidence_from_posterior,
    load_terrain_likelihood_rules,
    update_categorical_posterior,
    update_obstacle_posterior,
    update_traversability_posterior,
)

__all__ = [
    "BayesianStateLayer",
    "CategoricalBayesianStateLayer",
    "ConfidenceComponent",
    "ConfidenceUpdateReport",
    "ConfidenceWeights",
    "ObservationModelResult",
    "TerrainLikelihoodRules",
    "compute_terrain_category_likelihood",
    "default_confidence_config_path",
    "default_terrain_likelihood_config_path",
    "derive_confidence_from_categorical_posterior",
    "derive_confidence_from_posterior",
    "compute_consistency_confidence",
    "compute_observation_confidence",
    "compute_observation_model",
    "compute_recency_confidence",
    "compute_resolution_confidence",
    "fuse_confidence",
    "load_confidence_weights",
    "load_terrain_likelihood_rules",
    "update_categorical_posterior",
    "update_obstacle_posterior",
    "update_traversability_posterior",
    "update_confidence_from_observation",
]
